### ISSUE TITLE
Syntax error in setup.py file

### ISSUE THREAD

**Issue by diptichaudhari24** [jollychang/robotframework-appiumlibrary#35]
When I cloned this issue on my windows machine I could not install the package due to following syntax error:

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from ez_setup import use_setuptools
  File "src\ez_setup.py", line 106
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax

**Comment by jollychang** [comment]
What's you command?
I have try pip and python setup.py, both works
as you console log mentions, maybe it is a VersionConflict
http://stackoverflow.com/questions/12029284/ez-setup-py-syntax-error


```
(VENV)[jollychang@jollychangs-MBP robotframework-appiumlibrary]$ pip install -U robotframework-appiumlibrary
Requirement already up-to-date: robotframework-appiumlibrary in ./VENV/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.3-py2.7.egg
Requirement already up-to-date: decorator>=3.3.2 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: robotframework>=2.6.0 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: docutils>=0.8.1 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: Appium-Python-Client>=0.5 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: mock>=1.0.1 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-cov>=1.8.1 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-xdist>=1.11 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-pythonpath>=0.4 in ./VENV/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: selenium>=2.41.0 in ./VENV/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: enum34 in ./VENV/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: py>=1.4.22 in ./VENV/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: pytest>=2.6.0 in ./VENV/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: coverage>=3.7.1,<4.0a1 in ./VENV/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: cov-core>=1.14.0 in ./VENV/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: execnet>=1.1 in ./VENV/lib/python2.7/site-packages (from pytest-xdist>=1.11->robotframework-appiumlibrary)
Cleaning up...
```

```
(VENV)[jollychang@jollychangs-MBP robotframework-appiumlibrary]$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to src/robotframework_appiumlibrary.egg-info/requires.txt
writing src/robotframework_appiumlibrary.egg-info/PKG-INFO
writing top-level names to src/robotframework_appiumlibrary.egg-info/top_level.txt
writing dependency_links to src/robotframework_appiumlibrary.egg-info/dependency_links.txt
reading manifest file 'src/robotframework_appiumlibrary.egg-info/SOURCES.txt'
writing manifest file 'src/robotframework_appiumlibrary.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
copying src/AppiumLibrary/__init__.py -> build/lib/AppiumLibrary
copying src/AppiumLibrary/version.py -> build/lib/AppiumLibrary
copying src/AppiumLibrary/keywords/_applicationmanagement.py -> build/lib/AppiumLibrary/keywords
copying src/AppiumLibrary/keywords/_element.py -> build/lib/AppiumLibrary/keywords
copying src/AppiumLibrary/keywords/_runonfailure.py -> build/lib/AppiumLibrary/keywords
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary
copying build/lib/AppiumLibrary/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary
creating build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_applicationmanagement.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_element.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_keyevent.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_logging.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_runonfailure.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_screenshot.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_touch.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/_waiting.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
copying build/lib/AppiumLibrary/keywords/keywordgroup.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords
creating build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/locators
copying build/lib/AppiumLibrary/locators/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/locators
copying build/lib/AppiumLibrary/locators/elementfinder.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/locators
creating build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/utils
copying build/lib/AppiumLibrary/utils/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/utils
copying build/lib/AppiumLibrary/utils/applicationcache.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/utils
copying build/lib/AppiumLibrary/version.py -> build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary
copying build/lib/ez_setup.py -> build/bdist.macosx-10.9-x86_64/egg
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_applicationmanagement.py to _applicationmanagement.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_element.py to _element.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_keyevent.py to _keyevent.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_logging.py to _logging.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_runonfailure.py to _runonfailure.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_screenshot.py to _screenshot.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_touch.py to _touch.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/_waiting.py to _waiting.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/keywords/keywordgroup.py to keywordgroup.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/locators/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/locators/elementfinder.py to elementfinder.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/utils/applicationcache.py to applicationcache.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/AppiumLibrary/version.py to version.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/ez_setup.py to ez_setup.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/robotframework_appiumlibrary.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/robotframework_appiumlibrary.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/robotframework_appiumlibrary.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/robotframework_appiumlibrary.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/robotframework_appiumlibrary.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ez_setup: module MAY be using inspect.getsourcefile
AppiumLibrary.__init__: module references __file__
AppiumLibrary.keywords._applicationmanagement: module references __file__
creating 'dist/robotframework_appiumlibrary-1.2.3-py2.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing robotframework_appiumlibrary-1.2.3-py2.7.egg
creating /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.3-py2.7.egg
Extracting robotframework_appiumlibrary-1.2.3-py2.7.egg to /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Adding robotframework-appiumlibrary 1.2.3 to easy-install.pth file

Installed /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.3-py2.7.egg
Processing dependencies for robotframework-appiumlibrary==1.2.3
Searching for pytest-pythonpath==0.5
Best match: pytest-pythonpath 0.5
Adding pytest-pythonpath 0.5 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for pytest-xdist==1.11
Best match: pytest-xdist 1.11
Adding pytest-xdist 1.11 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for pytest-cov==1.8.1
Best match: pytest-cov 1.8.1
Adding pytest-cov 1.8.1 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for mock==1.0.1
Best match: mock 1.0.1
Adding mock 1.0.1 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for Appium-Python-Client==0.11
Best match: Appium-Python-Client 0.11
Adding Appium-Python-Client 0.11 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for docutils==0.12
Best match: docutils 0.12
Adding docutils 0.12 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for robotframework==2.8.6
Best match: robotframework 2.8.6
Adding robotframework 2.8.6 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for decorator==3.4.0
Best match: decorator 3.4.0
Adding decorator 3.4.0 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for pytest==2.6.4
Best match: pytest 2.6.4
Adding pytest 2.6.4 to easy-install.pth file
Installing py.test-2.7 script to /Users/jollychang/works/robotframework-appiumlibrary/VENV/bin
Installing py.test script to /Users/jollychang/works/robotframework-appiumlibrary/VENV/bin

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for py==1.4.26
Best match: py 1.4.26
Adding py 1.4.26 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for execnet==1.2.0
Best match: execnet 1.2.0
Adding execnet 1.2.0 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for cov-core==1.15.0
Best match: cov-core 1.15.0
Adding cov-core 1.15.0 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for coverage==3.7.1
Best match: coverage 3.7.1
Adding coverage 3.7.1 to easy-install.pth file
Installing coverage2 script to /Users/jollychang/works/robotframework-appiumlibrary/VENV/bin
Installing coverage-2.7 script to /Users/jollychang/works/robotframework-appiumlibrary/VENV/bin
Installing coverage script to /Users/jollychang/works/robotframework-appiumlibrary/VENV/bin

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for enum34==1.0.4
Best match: enum34 1.0.4
Adding enum34 1.0.4 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Searching for selenium==2.44.0
Best match: selenium 2.44.0
Adding selenium 2.44.0 to easy-install.pth file

Using /Users/jollychang/works/robotframework-appiumlibrary/VENV/lib/python2.7/site-packages
Finished processing dependencies for robotframework-appiumlibrary==1.2.3
```

**Comment by calaldees** [comment]
@diptichaudhari24 your error is because you are using python3.x and not python2.x
I got bitten by this because I built a python virtualenv and it used python3 by default
`virtualenv --no-site-packages python_env`
I corrected it with specifying python2.x explicitly
`virtualenv --no-site-packages -p python python_env`
