### ISSUE TITLE
Unable to install the package in Python 3.4

### ISSUE THREAD

**Issue by calshankar** [jollychang/robotframework-appiumlibrary#43]
Noticing below error in my Mac machine running OSX 10.9. Both setuptools & ez_setup package is installed

  error: invalid command 'bdist_egg'
    
    /private/var/folders/xz/j9r51m2j0z96s__wj_mv5cb40000gn/T/pycharm-packaging0.tmp/robotframework-appiumlibrary/distribute-0.6.14-py3.4.egg
    
    Traceback (most recent call last):
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ez_setup.py", line 143, in use_setuptools
    
        raise ImportError
    
    ImportError
       
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/xz/j9r51m2j0z96s__wj_mv5cb40000gn/T/pycharm-packaging0.tmp/robotframework-appiumlibrary/setup.py", line 8, in <module>
    
        use_setuptools()
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ez_setup.py", line 145, in use_setuptools
    
        return _do_download(version, download_base, to_dir, download_delay)
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ez_setup.py", line 125, in _do_download
    
        _build_egg(egg, tarball, to_dir)
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ez_setup.py", line 116, in _build_egg
    
        raise IOError('Could not build the egg.')
    
    OSError: Could not build the egg.

**Comment by jollychang** [comment]
It does not support python 3.X

**Comment by calshankar** [comment]
That was wickedly fast! I guess we should add this in the documentation

**Comment by jollychang** [comment]
updated https://github.com/jollychang/robotframework-appiumlibrary/commit/1c054551f0f2dea94d136c8439b2615b4d860445
